### ISSUE TITLE
关于“join us"

### ISSUE THREAD

**Issue by hcp4715** [Chuan-Peng-Lab/Lab_homepage#2]
现在的只有英文版，中文版没有，可以把公众号上关于招生信息的内容复制上来，作为中文的join us。
因为我们的主要界面是英文，所以在英文的join us里，加上一个类似于"For Students in mainland China, please see this blogpost for details"，从而转跳到中文的说明。
此外，英文版目前还比较缺少个性化，咱们后续还需要改进。

**Comment by yuki-961004** [comment]
已完成中文的join us
